package au.com.nakornthai.notification.domain;
public enum NotificationType { RESERVATION_CONFIRMED, RESERVATION_RECEIVED, RESERVATION_CANCELLED, RESERVATION_DECLINED, ORDER_RECEIVED, ORDER_ACCEPTED, ORDER_READY, ORDER_CANCELLED }
