import { getRestaurantAvailability } from '../../restaurant/api/restaurantApi';
import { useEffect, useState } from 'react';
import { useAuth } from '../../identity/model/AuthContext';
import { reservationRequest } from '../api/reservationApi';
const today=(timeZone)=>new Intl.DateTimeFormat('en-CA',{timeZone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const transitions={REQUESTED:['CONFIRMED','DECLINED','CANCELLED'],CONFIRMED:['SEATED','NO_SHOW','CANCELLED']};
export default function ReservationAdminPage() {
 const {authorization}=useAuth();const [date,setDate]=useState(''),[timezone,setTimezone]=useState(''),[rows,setRows]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notes,setNotes]=useState({});
 useEffect(()=>{let active=true;getRestaurantAvailability().then(data=>{if(active){setTimezone(data.timezone);setDate(today(data.timezone));}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[]);
 async function load(){setBusy(true);setError('');try{setRows(await reservationRequest(`/staff/reservations?date=${date}`,{authorization}));}catch(e){setError(e.message);}finally{setBusy(false);}}
 useEffect(()=>{if(!date)return;let active=true;setBusy(true);setError('');setRows([]);reservationRequest(`/staff/reservations?date=${date}`,{authorization}).then(data=>{if(active)setRows(data);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;};},[date,authorization]);
 async function update(row,status){setBusy(true);setError('');try{await reservationRequest(`/staff/reservations/${row.id}`,{method:'PATCH',authorization,body:{version:row.version,status,staffNote:notes[row.id]??row.staffNote}});setRows(await reservationRequest(`/staff/reservations?date=${date}`,{authorization}));}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <main className="staff-menu page-width"><a href="#/staff">Staff home</a><h1>Reservations</h1><p>Check table availability and contact the guest before confirming. No automatic email or SMS is sent.</p><div className="staff-toolbar"><label>Restaurant date ({timezone || 'loading…'})<input type="date" value={date} required disabled={busy} onChange={e=>{if(e.target.value)setDate(e.target.value);}} /></label><button disabled={busy || !date} onClick={load}>Refresh bookings</button></div>
 {error&&<p className="staff-error" role="alert">{error}</p>}{busy&&<p role="status">Updating bookings…</p>}{!busy&&!error&&!rows.length&&<p>No booking requests for this date.</p>}
 <div className="order-queue">{rows.map(row=><article className="order-panel" key={row.id}><h2>{row.requestedAt.slice(11,16)} · {row.customerName}</h2><p>{row.partySize} guests · {row.status.replaceAll('_',' ')}</p><p>Phone: {row.phone}</p>{row.notes&&<p>Guest notes: {row.notes}</p>}<small>Reference: {row.id}</small>{transitions[row.status]?<><label>Staff note<textarea disabled={busy} maxLength={500} value={notes[row.id]??row.staffNote} onChange={e=>setNotes({...notes,[row.id]:e.target.value})}/></label><div className="staff-toolbar">{transitions[row.status].map(status=><button disabled={busy||!!error} key={status} onClick={()=>update(row,status)}>{status.replaceAll('_',' ')}</button>)}</div></>:<p>{row.staffNote}</p>}{row.updatedBy&&<small>Last updated by {row.updatedBy}</small>}</article>)}</div></main>;
}
